/*
  # Featured Playlists (Reseed)
  - Generated by scripts/build_featured_playlists.cjs
  - Uses TMDB data to ensure correct IDs and images
*/

-- Remove existing featured playlists
DELETE FROM playlist_movies WHERE playlist_id IN ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000005', '00000000-0000-0000-0000-000000000006', '00000000-0000-0000-0000-000000000007', '00000000-0000-0000-0000-000000000008', '00000000-0000-0000-0000-000000000009');
DELETE FROM playlists WHERE id IN ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000003', '00000000-0000-0000-0000-000000000004', '00000000-0000-0000-0000-000000000005', '00000000-0000-0000-0000-000000000006', '00000000-0000-0000-0000-000000000007', '00000000-0000-0000-0000-000000000008', '00000000-0000-0000-0000-000000000009');

-- Insert curated featured playlists
INSERT INTO playlists (id, user_id, title, description, cover_image, is_public, is_featured, created_at) VALUES
  ('00000000-0000-0000-0000-000000000001', NULL, 'Animated Classics', 'The very best animated films from around the world', 'https://image.tmdb.org/t/p/w780', true, true, now()),
  ('00000000-0000-0000-0000-000000000002', NULL, 'Horror Essentials', 'Must-watch horror films that defined the genre', 'https://image.tmdb.org/t/p/w780', true, true, now()),
  ('00000000-0000-0000-0000-000000000003', NULL, 'Romance Classics', 'Timeless love stories that capture the heart', 'https://image.tmdb.org/t/p/w780', true, true, now()),
  ('00000000-0000-0000-0000-000000000004', NULL, 'Comedy Classics', 'The funniest films ever made', 'https://image.tmdb.org/t/p/w780', true, true, now()),
  ('00000000-0000-0000-0000-000000000005', NULL, 'Adventure Epics', 'Epic adventures that take you on incredible journeys', 'https://image.tmdb.org/t/p/w780', true, true, now()),
  ('00000000-0000-0000-0000-000000000006', NULL, 'Crime Masterpieces', 'The greatest crime films ever crafted', 'https://image.tmdb.org/t/p/w780', true, true, now()),
  ('00000000-0000-0000-0000-000000000007', NULL, 'Family Favorites', 'Perfect films for the whole family to enjoy', 'https://image.tmdb.org/t/p/w780', true, true, now()),
  ('00000000-0000-0000-0000-000000000008', NULL, 'Fantasy Epics', 'Magical worlds and extraordinary adventures', 'https://image.tmdb.org/t/p/w780', true, true, now()),
  ('00000000-0000-0000-0000-000000000009', NULL, 'Sci-Fi Classics', 'Visionary science fiction that shaped the future', 'https://image.tmdb.org/t/p/w780', true, true, now())
ON CONFLICT (id) DO NOTHING;

-- Animated Classics
UPDATE playlists SET cover_image = 'https://image.tmdb.org/t/p/w780/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg' WHERE id = '00000000-0000-0000-0000-000000000001';
INSERT INTO playlist_movies (playlist_id, movie_id, movie_title, movie_poster, movie_backdrop, movie_rating, movie_year, order_index) VALUES
  ('00000000-0000-0000-0000-000000000001', 129, 'Spirited Away', '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', '/6oaL4DP75yABrd5EbC4H2zq5ghc.jpg', 8.5, 2001, 1),
  ('00000000-0000-0000-0000-000000000001', 8587, 'The Lion King', '/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg', '/wXsQvli6tWqja51pYxXNG1LFIGV.jpg', 8.3, 1994, 2),
  ('00000000-0000-0000-0000-000000000001', 10020, 'Beauty and the Beast', '/hUJ0UvQ5tgE2Z9WpfuduVSdiCiU.jpg', '/fW4ZCoEZRBqLAJGFQ2g5AdAfPQR.jpg', 7.7, 1991, 3),
  ('00000000-0000-0000-0000-000000000001', 862, 'Toy Story', '/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg', '/3Rfvhy1Nl6sSGJwyjb0QiZzZYlB.jpg', 8.0, 1995, 4),
  ('00000000-0000-0000-0000-000000000001', 128, 'Princess Mononoke', '/cMYCDADoLKLbB83g4WnJegaZimC.jpg', '/gl0jzn4BupSbL2qMVeqrjKkF9Js.jpg', 8.3, 1997, 5),
  ('00000000-0000-0000-0000-000000000001', 10681, 'WALL·E', '/hbhFnRzzg6ZDmm8YAmxBnQpQIPh.jpg', '/3CvNc04vTwTir5q3LBDuvUb8Ng6.jpg', 8.1, 2008, 6),
  ('00000000-0000-0000-0000-000000000001', 8392, 'My Neighbor Totoro', '/rtGDOeG9LzoerkDGZF9dnVeLppL.jpg', '/95ozIP0A2fKaAXxwDxUEVn74Iux.jpg', 8.1, 1988, 7),
  ('00000000-0000-0000-0000-000000000001', 10386, 'The Iron Giant', '/ct04FCFLPImNG5thcPLRnVsZlmS.jpg', '/wfClZdRb1x4LZ8B73Y9RSn8XAPa.jpg', 8.0, 1999, 8),
  ('00000000-0000-0000-0000-000000000001', 408, 'Snow White and the Seven Dwarfs', '/3VAHfuNb6Z7UiW12iYKANSPBl8m.jpg', '/wmSxNVGZOV1A51Yx6ChDXk3NVVi.jpg', 7.1, 1938, 9),
  ('00000000-0000-0000-0000-000000000001', 10895, 'Pinocchio', '/bnZJrLRnoQHpzEJdka1KYfsAF3N.jpg', '/iFPpb2KIWKwBfyqSJivE4JegFPP.jpg', 7.1, 1940, 10)
ON CONFLICT (playlist_id, movie_id) DO NOTHING;

-- Horror Essentials
UPDATE playlists SET cover_image = 'https://image.tmdb.org/t/p/w780/5x0CeVHJI8tcDx8tUUwYHQSNILq.jpg' WHERE id = '00000000-0000-0000-0000-000000000002';
INSERT INTO playlist_movies (playlist_id, movie_id, movie_title, movie_poster, movie_backdrop, movie_rating, movie_year, order_index) VALUES
  ('00000000-0000-0000-0000-000000000002', 9552, 'The Exorcist', '/5x0CeVHJI8tcDx8tUUwYHQSNILq.jpg', '/xcjJ5khg2yzOa282mza39Lbrm7j.jpg', 7.7, 1973, 1),
  ('00000000-0000-0000-0000-000000000002', 948, 'Halloween', '/wijlZ3HaYMvlDTPqJoTCWKFkCPU.jpg', '/aRka9neADW1M0Zf9lF8kW2jEgXe.jpg', 7.6, 1978, 2),
  ('00000000-0000-0000-0000-000000000002', 694, 'The Shining', '/xazWoLealQwEgqZ89MLZklLZD3k.jpg', '/mmd1HnuvAzFc4iuVJcnBrhDNEKr.jpg', 8.2, 1980, 3),
  ('00000000-0000-0000-0000-000000000002', 539, 'Psycho', '/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg', '/uif5fUshJrXyyDzfpzp1DLw3N0S.jpg', 8.4, 1960, 4),
  ('00000000-0000-0000-0000-000000000002', 348, 'Alien', '/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg', '/AmR3JG1VQVxU8TfAvljUhfSFUOx.jpg', 8.2, 1979, 5),
  ('00000000-0000-0000-0000-000000000002', 274, 'The Silence of the Lambs', '/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg', '/aYcnDyLMnpKce1FOYUpZrXtgUye.jpg', 8.3, 1991, 6),
  ('00000000-0000-0000-0000-000000000002', 4232, 'Scream', '/lr9ZIrmuwVmZhpZuTCW8D9g0ZJe.jpg', '/4PPC7fKClu0u7NTbo5xgV4vb5VD.jpg', 7.4, 1996, 7),
  ('00000000-0000-0000-0000-000000000002', 578, 'Jaws', '/lxM6kqilAdpdhqUl2biYp5frUxE.jpg', '/xgU3KkqiME9pGe5gGCNpUYkoSWg.jpg', 7.7, 1975, 8),
  ('00000000-0000-0000-0000-000000000002', 571, 'The Birds', '/eClg8QPg8mwB6INIC4pyR5pAbDr.jpg', '/il5zDHC5sGe3ZHLhVi3tNFZ9Tt5.jpg', 7.5, 1963, 9),
  ('00000000-0000-0000-0000-000000000002', 1091, 'The Thing', '/tzGY49kseSE9QAKk47uuDGwnSCu.jpg', '/jaO8WurWoUBE55nskqtFqPZFFaO.jpg', 8.1, 1982, 10)
ON CONFLICT (playlist_id, movie_id) DO NOTHING;

-- Romance Classics
UPDATE playlists SET cover_image = 'https://image.tmdb.org/t/p/w780/oyGRZVIthHJjc98ekKpeWpDh8Ws.jpg' WHERE id = '00000000-0000-0000-0000-000000000003';
INSERT INTO playlist_movies (playlist_id, movie_id, movie_title, movie_poster, movie_backdrop, movie_rating, movie_year, order_index) VALUES
  ('00000000-0000-0000-0000-000000000003', 289, 'Casablanca', '/oyGRZVIthHJjc98ekKpeWpDh8Ws.jpg', '/87wqeMeUeMRLjsE1IWNKJcPlpuC.jpg', 8.2, 1943, 1),
  ('00000000-0000-0000-0000-000000000003', 2493, 'The Princess Bride', '/dvjqlp2sAhUeFjUOfQDgqwpphHj.jpg', '/aQ2ZbNqIaecoQsryNe33UmDtms.jpg', 7.7, 1987, 2),
  ('00000000-0000-0000-0000-000000000003', 597, 'Titanic', '/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg', '/tupgjqhWx5oieQrdyesO3aclUX9.jpg', 7.9, 1997, 3),
  ('00000000-0000-0000-0000-000000000003', 11036, 'The Notebook', '/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg', '/bWoa6FtpnD2qByTVTmL5pAZUAKv.jpg', 7.9, 2004, 4),
  ('00000000-0000-0000-0000-000000000003', 114, 'Pretty Woman', '/hVHUfT801LQATGd26VPzhorIYza.jpg', '/sGEqHTylawwS6hwKultk1mKUjdB.jpg', 7.5, 1990, 5),
  ('00000000-0000-0000-0000-000000000003', 251, 'Ghost', '/w9RaPHov8oM5cnzeE27isnFMsvS.jpg', '/6nLdSON3ErniBZTXWG7WRqs5jGz.jpg', 7.2, 1990, 6),
  ('00000000-0000-0000-0000-000000000003', 639, 'When Harry Met Sally...', '/rFOiFUhTMtDetqCGClC9PIgnC1P.jpg', '/dbdegCWeD4iK5LXxSBjGdIRsVXS.jpg', 7.4, 1989, 7),
  ('00000000-0000-0000-0000-000000000003', 804, 'Roman Holiday', '/8lI9dmz1RH20FAqltkGelY1v4BE.jpg', '/6f50k0bAekjxDvVvGC1SupJSzf4.jpg', 7.9, 1953, 8),
  ('00000000-0000-0000-0000-000000000003', 88, 'Dirty Dancing', '/9Jw6jys7q9gjzVX5zm1z0gC8gY9.jpg', '/6iDQCBUSZKzY8Rnu8ECwl2gXcfG.jpg', 7.3, 1987, 9),
  ('00000000-0000-0000-0000-000000000003', 770, 'Gone with the Wind', '/lNz2Ow0wGCAvzckW7EOjE03KcYv.jpg', '/ft8WRF2xqEwwGWa59naDUybKTAx.jpg', 7.9, 1939, 10)
ON CONFLICT (playlist_id, movie_id) DO NOTHING;

-- Comedy Classics
UPDATE playlists SET cover_image = 'https://image.tmdb.org/t/p/w780/hVIKyTK13AvOGv7ICmJjK44DTzp.jpg' WHERE id = '00000000-0000-0000-0000-000000000004';
INSERT INTO playlist_movies (playlist_id, movie_id, movie_title, movie_poster, movie_backdrop, movie_rating, movie_year, order_index) VALUES
  ('00000000-0000-0000-0000-000000000004', 239, 'Some Like It Hot', '/hVIKyTK13AvOGv7ICmJjK44DTzp.jpg', '/5zTwAcnI3zCJ0mucPPnoBtkSWEV.jpg', 8.1, 1959, 1),
  ('00000000-0000-0000-0000-000000000004', 813, 'Airplane!', '/7Q3efxd3AF1vQjlSxnlerSA7RzN.jpg', '/lz6Cy1JgOR72AilU2ghDvLKbgqT.jpg', 7.3, 1980, 2),
  ('00000000-0000-0000-0000-000000000004', 115, 'The Big Lebowski', '/9mprbw31MGdd66LR0AQKoDMoFRv.jpg', '/ti6kJ80ZB8RZTiDIzPkhaCJMoqq.jpg', 7.8, 1998, 3),
  ('00000000-0000-0000-0000-000000000004', 137, 'Groundhog Day', '/gCgt1WARPZaXnq523ySQEUKinCs.jpg', '/ttBydD0SynC0TMkW3AcnmsySkLp.jpg', 7.6, 1993, 4),
  ('00000000-0000-0000-0000-000000000004', 3034, 'Young Frankenstein', '/c6335WJCZO8NK5wehHk5sA9Cypv.jpg', '/rsI82F7DadIQcrZyPbuwmkhN5ty.jpg', 7.9, 1974, 5),
  ('00000000-0000-0000-0000-000000000004', 11072, 'Blazing Saddles', '/vNw1gOEDdYTDeNMuuq8OmiEHrfH.jpg', '/syUzOlwPqM8pGRhUxPOnmrcGcHb.jpg', 7.2, 1974, 6),
  ('00000000-0000-0000-0000-000000000004', 935, 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', '/7SixLzxcqezkZEYU8pcHZgbkmjp.jpg', '/sTp8K0SfcC2RQef1Tu160z3niHO.jpg', 8.1, 1964, 7),
  ('00000000-0000-0000-0000-000000000004', 703, 'Annie Hall', '/dEtjPywhDbAXYjoFfhBC4U9unU7.jpg', '/8n9dYsTbXTykzm2Nuy7R2ftapXQ.jpg', 7.7, 1977, 8),
  ('00000000-0000-0000-0000-000000000004', 620, 'Ghostbusters', '/7E8nLijS9AwwUEPu2oFYOVKhdFA.jpg', '/c6yfABGVKuB5cjoOwdX4AJMlzUz.jpg', 7.5, 1984, 9),
  ('00000000-0000-0000-0000-000000000004', 762, 'Monty Python and the Holy Grail', '/hWx1ANiWEWWyzKPN0us35HCGnhQ.jpg', '/1KgXxv6tHXOnakqYvMPvFwYKWiw.jpg', 7.8, 1975, 10)
ON CONFLICT (playlist_id, movie_id) DO NOTHING;

-- Adventure Epics
UPDATE playlists SET cover_image = 'https://image.tmdb.org/t/p/w780/ceG9VzoRAVGwivFU403Wc3AHRys.jpg' WHERE id = '00000000-0000-0000-0000-000000000005';
INSERT INTO playlist_movies (playlist_id, movie_id, movie_title, movie_poster, movie_backdrop, movie_rating, movie_year, order_index) VALUES
  ('00000000-0000-0000-0000-000000000005', 85, 'Raiders of the Lost Ark', '/ceG9VzoRAVGwivFU403Wc3AHRys.jpg', '/ueDw7djPgKPZfph0vC43aD2EMyF.jpg', 7.9, 1981, 1),
  ('00000000-0000-0000-0000-000000000005', 120, 'The Lord of the Rings: The Fellowship of the Ring', '/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg', '/x2RS3uTcsJJ9IfjNPcgDmukoEcQ.jpg', 8.4, 2001, 2),
  ('00000000-0000-0000-0000-000000000005', 121, 'The Lord of the Rings: The Two Towers', '/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg', '/jfEOzpsjc6JDlKhUHb4toWQPt.jpg', 8.4, 2002, 3),
  ('00000000-0000-0000-0000-000000000005', 122, 'The Lord of the Rings: The Return of the King', '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg', '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg', 8.5, 2003, 4),
  ('00000000-0000-0000-0000-000000000005', 947, 'Lawrence of Arabia', '/AiAm0EtDvyGqNpVoieRw4u65vD1.jpg', '/nKwGUiqPdNf47XFjlbR5IFwAaOL.jpg', 8.0, 1962, 5),
  ('00000000-0000-0000-0000-000000000005', 10907, 'The Adventures of Robin Hood', '/4mazyXEMkmLw5h6076yyNSm9uv0.jpg', '/yjnfM8QmrXQkWl8dUimsDGl73el.jpg', 7.5, 1938, 6),
  ('00000000-0000-0000-0000-000000000005', 213, 'North by Northwest', '/kNOFPQrel9YFCVzI0DF8FnCEpCw.jpg', '/fONtQBk12LGjQo4q6bXDROVQmTy.jpg', 8.0, 1959, 7),
  ('00000000-0000-0000-0000-000000000005', 826, 'The Bridge on the River Kwai', '/7paXMt2e3Tr5dLmEZOGgFEn2Vo7.jpg', '/EcQKZcVYZ8EjK3eN1quPvkMrL9.jpg', 7.8, 1957, 8),
  ('00000000-0000-0000-0000-000000000005', 3090, 'The Treasure of the Sierra Madre', '/pWcst7zVbi8Z8W6GFrdNE7HHRxL.jpg', '/sj5R5SGor3YMFBuabMj8gPbyBmh.jpg', 8.0, 1948, 9),
  ('00000000-0000-0000-0000-000000000005', 488, 'The African Queen', '/2Ypg0KhQfFYWILelvHGtSHHR0dk.jpg', '/doTKdtLfn2b7ZmeElmT6ZDW3XIk.jpg', 7.4, 1952, 10)
ON CONFLICT (playlist_id, movie_id) DO NOTHING;

-- Crime Masterpieces
UPDATE playlists SET cover_image = 'https://image.tmdb.org/t/p/w780/3bhkrj58Vtu7enYsRolD1fZdja1.jpg' WHERE id = '00000000-0000-0000-0000-000000000006';
INSERT INTO playlist_movies (playlist_id, movie_id, movie_title, movie_poster, movie_backdrop, movie_rating, movie_year, order_index) VALUES
  ('00000000-0000-0000-0000-000000000006', 238, 'The Godfather', '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', '/htuuuEwAvDVECMpb0ltLLyZyDDt.jpg', 8.7, 1972, 1),
  ('00000000-0000-0000-0000-000000000006', 240, 'The Godfather Part II', '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg', '/kGzFbGhp99zva6oZODW5atUtnqi.jpg', 8.6, 1974, 2),
  ('00000000-0000-0000-0000-000000000006', 769, 'GoodFellas', '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg', '/7TF4p86ZafnxFuNqWdhpHXFO244.jpg', 8.5, 1990, 3),
  ('00000000-0000-0000-0000-000000000006', 680, 'Pulp Fiction', '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg', '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg', 8.5, 1994, 4),
  ('00000000-0000-0000-0000-000000000006', 111, 'Scarface', '/iQ5ztdjvteGeboxtmRdXEChJOHh.jpg', '/sctvs9cUwJD15qlTlrsh2BXsK75.jpg', 8.2, 1983, 5),
  ('00000000-0000-0000-0000-000000000006', 1422, 'The Departed', '/nT97ifVT2J1yMQmeq20Qblg61T.jpg', '/6WRrGYalXXveItfpnipYdayFkQB.jpg', 8.2, 2006, 6),
  ('00000000-0000-0000-0000-000000000006', 524, 'Casino', '/gziIkUSnYuj9ChCi8qOu2ZunpSC.jpg', '/iZGiMD0p1M2AOmzKknFo5bkuz94.jpg', 8.0, 1995, 7),
  ('00000000-0000-0000-0000-000000000006', 949, 'Heat', '/umSVjVdbVwtx5ryCA2QXL44Durm.jpg', '/5JaR6UEoCJJLtLpqFOVMY4O4R7P.jpg', 7.9, 1995, 8),
  ('00000000-0000-0000-0000-000000000006', 829, 'Chinatown', '/kZRSP3FmOcq0xnBulqpUQngJUXY.jpg', '/eJ6kPtua2rEvjxHdCtnIobXJZSf.jpg', 7.9, 1974, 9),
  ('00000000-0000-0000-0000-000000000006', 963, 'The Maltese Falcon', '/bf4o6Uzw5wqLjdKwRuiDrN1xyvl.jpg', '/9xzVKUGbVKrrgwlmshJ8SxI5mL7.jpg', 7.7, 1941, 10)
ON CONFLICT (playlist_id, movie_id) DO NOTHING;

-- Family Favorites
UPDATE playlists SET cover_image = 'https://image.tmdb.org/t/p/w780/an0nD6uq6byfxXCfk6lQBzdL2J1.jpg' WHERE id = '00000000-0000-0000-0000-000000000007';
INSERT INTO playlist_movies (playlist_id, movie_id, movie_title, movie_poster, movie_backdrop, movie_rating, movie_year, order_index) VALUES
  ('00000000-0000-0000-0000-000000000007', 601, 'E.T. the Extra-Terrestrial', '/an0nD6uq6byfxXCfk6lQBzdL2J1.jpg', '/mXLVA0YL6tcXi6SJSuAh9ONXFj5.jpg', 7.5, 1982, 1),
  ('00000000-0000-0000-0000-000000000007', 630, 'The Wizard of Oz', '/pfAZFD7I2hxW9HCChTuAzsdE6UX.jpg', '/qAvou7F5P4VcIR72JzzrnKEQSN3.jpg', 7.6, 1939, 2),
  ('00000000-0000-0000-0000-000000000007', 433, 'Mary Poppins', '/ei8hhYCMfURfPOXKBnyl61be2iV.jpg', '/t07Pdtl3rTbE5mBdV8hAggHcGVN.jpg', 7.6, 1964, 3),
  ('00000000-0000-0000-0000-000000000007', 15121, 'The Sound of Music', '/c6CrUZypAsBCaRWX0M3RVRDbhNS.jpg', '/ioQYjcRnU54ir5ltgyS7k53zw5x.jpg', 7.7, 1965, 4),
  ('00000000-0000-0000-0000-000000000007', 771, 'Home Alone', '/i5We88HdO9Nsrv8xLyo4toNsLUM.jpg', '/vaVaNrscmsG8CUKYxiwZGFNqGJo.jpg', 7.4, 1990, 5),
  ('00000000-0000-0000-0000-000000000007', 34584, 'The NeverEnding Story', '/ddYCa91iDXfJCxaqSYzwi2fjfnl.jpg', '/or6DXSUr7vhqwjFgxP4MqghYr6U.jpg', 7.2, 1984, 6),
  ('00000000-0000-0000-0000-000000000007', 2280, 'Big', '/eWhCDJiwxvx3YXkAFRiHjimnF0j.jpg', '/dGbBnTYxdHf1qyUgHsuFpxn1K4E.jpg', 7.2, 1988, 7),
  ('00000000-0000-0000-0000-000000000007', 1885, 'The Karate Kid', '/1mp4ViklKvA0WXXsNvNx0RBuiit.jpg', '/j1xaeJZOEOiVBD1rk3dg4YaAk23.jpg', 7.2, 1984, 8),
  ('00000000-0000-0000-0000-000000000007', 105, 'Back to the Future', '/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg', '/yz8QL8WFD8yj0LA5zIlNOgcHvZK.jpg', 8.3, 1985, 9),
  ('00000000-0000-0000-0000-000000000007', 11528, 'The Sandlot', '/7PYqz0viEuW8qTvuGinUMjDWMnj.jpg', '/kFm4FbjD2mBWtK9uyXryFtOD0Ut.jpg', 7.5, 1993, 10)
ON CONFLICT (playlist_id, movie_id) DO NOTHING;

-- Fantasy Epics
UPDATE playlists SET cover_image = 'https://image.tmdb.org/t/p/w780/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg' WHERE id = '00000000-0000-0000-0000-000000000008';
INSERT INTO playlist_movies (playlist_id, movie_id, movie_title, movie_poster, movie_backdrop, movie_rating, movie_year, order_index) VALUES
  ('00000000-0000-0000-0000-000000000008', 120, 'The Lord of the Rings: The Fellowship of the Ring', '/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg', '/x2RS3uTcsJJ9IfjNPcgDmukoEcQ.jpg', 8.4, 2001, 1),
  ('00000000-0000-0000-0000-000000000008', 121, 'The Lord of the Rings: The Two Towers', '/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg', '/jfEOzpsjc6JDlKhUHb4toWQPt.jpg', 8.4, 2002, 2),
  ('00000000-0000-0000-0000-000000000008', 122, 'The Lord of the Rings: The Return of the King', '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg', '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg', 8.5, 2003, 3),
  ('00000000-0000-0000-0000-000000000008', 630, 'The Wizard of Oz', '/pfAZFD7I2hxW9HCChTuAzsdE6UX.jpg', '/qAvou7F5P4VcIR72JzzrnKEQSN3.jpg', 7.6, 1939, 4),
  ('00000000-0000-0000-0000-000000000008', 1417, 'Pan''s Labyrinth', '/s8C4whhKtDaJvMDcyiMvx3BIF5F.jpg', '/6G6nqSW9S7EHA9HrYl0Z8uo2H7f.jpg', 7.8, 2006, 5),
  ('00000000-0000-0000-0000-000000000008', 2493, 'The Princess Bride', '/dvjqlp2sAhUeFjUOfQDgqwpphHj.jpg', '/aQ2ZbNqIaecoQsryNe33UmDtms.jpg', 7.7, 1987, 6),
  ('00000000-0000-0000-0000-000000000008', 34584, 'The NeverEnding Story', '/ddYCa91iDXfJCxaqSYzwi2fjfnl.jpg', '/or6DXSUr7vhqwjFgxP4MqghYr6U.jpg', 7.2, 1984, 7),
  ('00000000-0000-0000-0000-000000000008', 162, 'Edward Scissorhands', '/e0FqKFvGPdQNWG8tF9cZBtev9Em.jpg', '/uNLIMPxknsV4n3IAEDpS1iqF5dm.jpg', 7.7, 1990, 8),
  ('00000000-0000-0000-0000-000000000008', 129, 'Spirited Away', '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', '/6oaL4DP75yABrd5EbC4H2zq5ghc.jpg', 8.5, 2001, 9),
  ('00000000-0000-0000-0000-000000000008', 674, 'Harry Potter and the Goblet of Fire', '/fECBtHlr0RB3foNHDiCBXeg9Bv9.jpg', '/8f9dnOtpArDrOMEylpSN9Sc6fuz.jpg', 7.8, 2005, 10)
ON CONFLICT (playlist_id, movie_id) DO NOTHING;

-- Sci-Fi Classics
UPDATE playlists SET cover_image = 'https://image.tmdb.org/t/p/w780/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg' WHERE id = '00000000-0000-0000-0000-000000000009';
INSERT INTO playlist_movies (playlist_id, movie_id, movie_title, movie_poster, movie_backdrop, movie_rating, movie_year, order_index) VALUES
  ('00000000-0000-0000-0000-000000000009', 62, '2001: A Space Odyssey', '/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg', '/w5IDXtifKntw0ajv2co7jFlTQDM.jpg', 8.1, 1968, 1),
  ('00000000-0000-0000-0000-000000000009', 78, 'Blade Runner', '/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg', '/qr7dUqleMRd0VgollazbmyP9XjI.jpg', 7.9, 1982, 2),
  ('00000000-0000-0000-0000-000000000009', 11, 'Star Wars', '/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg', '/2w4xG178RpB4MDAIfTkqAuSJzec.jpg', 8.2, 1977, 3),
  ('00000000-0000-0000-0000-000000000009', 603, 'The Matrix', '/p96dm7sCMn4VYAStA6siNz30G1r.jpg', '/8K9qHeM6G6QjQN0C5XKFGvK5lzM.jpg', 8.2, 1999, 4),
  ('00000000-0000-0000-0000-000000000009', 348, 'Alien', '/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg', '/AmR3JG1VQVxU8TfAvljUhfSFUOx.jpg', 8.2, 1979, 5),
  ('00000000-0000-0000-0000-000000000009', 601, 'E.T. the Extra-Terrestrial', '/an0nD6uq6byfxXCfk6lQBzdL2J1.jpg', '/mXLVA0YL6tcXi6SJSuAh9ONXFj5.jpg', 7.5, 1982, 6),
  ('00000000-0000-0000-0000-000000000009', 280, 'Terminator 2: Judgment Day', '/5M0j0B18abtBI5gi2RhfjjurTqb.jpg', '/vINgGecnz95iDL6fjQMARDsocgG.jpg', 8.1, 1991, 7),
  ('00000000-0000-0000-0000-000000000009', 105, 'Back to the Future', '/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg', '/yz8QL8WFD8yj0LA5zIlNOgcHvZK.jpg', 8.3, 1985, 8),
  ('00000000-0000-0000-0000-000000000009', 840, 'Close Encounters of the Third Kind', '/yaPx3cK9zGFX3SbcKwxWM1QIbUh.jpg', '/u9ZLyLvqHY5VDjn0Rs4LKAklsAV.jpg', 7.3, 1977, 9),
  ('00000000-0000-0000-0000-000000000009', 157336, 'Interstellar', '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', '/vgnoBSVzWAV9sNQUORaDGvDp7wx.jpg', 8.5, 2014, 10)
ON CONFLICT (playlist_id, movie_id) DO NOTHING;
